# Generated by Django 4.2.2 on 2023-07-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_servicemodel_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
