# Generated by Django 4.2.2 on 2023-07-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_servicemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='detailed_description',
            field=models.TextField(blank=True),
        ),
    ]
