# Generated by Django 4.2.2 on 2023-07-25 15:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_servicemodel_detailed_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemodel',
            name='detailed_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
