# Generated by Django 4.2.2 on 2023-07-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_servicemodel_detailed_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='sub_desction',
            field=models.TextField(blank=True),
        ),
    ]
